### YamlMime:ManagedReference
items:
- uid: TaleOfTiles.Journey.JourneyMapConfig
  commentId: T:TaleOfTiles.Journey.JourneyMapConfig
  id: JourneyMapConfig
  parent: TaleOfTiles.Journey
  children:
  - TaleOfTiles.Journey.JourneyMapConfig.#ctor(System.String,System.String,TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig[])
  - TaleOfTiles.Journey.JourneyMapConfig.blocks
  - TaleOfTiles.Journey.JourneyMapConfig.config_id
  - TaleOfTiles.Journey.JourneyMapConfig.map_id
  langs:
  - csharp
  - vb
  name: JourneyMapConfig
  nameWithType: JourneyMapConfig
  fullName: TaleOfTiles.Journey.JourneyMapConfig
  type: Class
  source:
    remote:
      path: Assets/Scripts/LevelGenerator/JourneyMap.cs
      branch: dev
      repo: https://github.com/ElementalMagic/Match-3-Mobile-Game.git
    id: JourneyMapConfig
    path: ../Assets/Scripts/LevelGenerator/JourneyMap.cs
    startLine: 66
  assemblies:
  - Assembly-CSharp
  namespace: TaleOfTiles.Journey
  syntax:
    content: >-
      [Serializable]

      public class JourneyMapConfig
    content.vb: >-
      <Serializable>

      Public Class JourneyMapConfig
  inheritance:
  - System.Object
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: TaleOfTiles.Journey.JourneyMapConfig.config_id
  commentId: F:TaleOfTiles.Journey.JourneyMapConfig.config_id
  id: config_id
  parent: TaleOfTiles.Journey.JourneyMapConfig
  langs:
  - csharp
  - vb
  name: config_id
  nameWithType: JourneyMapConfig.config_id
  fullName: TaleOfTiles.Journey.JourneyMapConfig.config_id
  type: Field
  source:
    remote:
      path: Assets/Scripts/LevelGenerator/JourneyMap.cs
      branch: dev
      repo: https://github.com/ElementalMagic/Match-3-Mobile-Game.git
    id: config_id
    path: ../Assets/Scripts/LevelGenerator/JourneyMap.cs
    startLine: 72
  assemblies:
  - Assembly-CSharp
  namespace: TaleOfTiles.Journey
  syntax:
    content: public string config_id
    return:
      type: System.String
    content.vb: Public config_id As String
- uid: TaleOfTiles.Journey.JourneyMapConfig.map_id
  commentId: F:TaleOfTiles.Journey.JourneyMapConfig.map_id
  id: map_id
  parent: TaleOfTiles.Journey.JourneyMapConfig
  langs:
  - csharp
  - vb
  name: map_id
  nameWithType: JourneyMapConfig.map_id
  fullName: TaleOfTiles.Journey.JourneyMapConfig.map_id
  type: Field
  source:
    remote:
      path: Assets/Scripts/LevelGenerator/JourneyMap.cs
      branch: dev
      repo: https://github.com/ElementalMagic/Match-3-Mobile-Game.git
    id: map_id
    path: ../Assets/Scripts/LevelGenerator/JourneyMap.cs
    startLine: 73
  assemblies:
  - Assembly-CSharp
  namespace: TaleOfTiles.Journey
  syntax:
    content: public string map_id
    return:
      type: System.String
    content.vb: Public map_id As String
- uid: TaleOfTiles.Journey.JourneyMapConfig.blocks
  commentId: F:TaleOfTiles.Journey.JourneyMapConfig.blocks
  id: blocks
  parent: TaleOfTiles.Journey.JourneyMapConfig
  langs:
  - csharp
  - vb
  name: blocks
  nameWithType: JourneyMapConfig.blocks
  fullName: TaleOfTiles.Journey.JourneyMapConfig.blocks
  type: Field
  source:
    remote:
      path: Assets/Scripts/LevelGenerator/JourneyMap.cs
      branch: dev
      repo: https://github.com/ElementalMagic/Match-3-Mobile-Game.git
    id: blocks
    path: ../Assets/Scripts/LevelGenerator/JourneyMap.cs
    startLine: 74
  assemblies:
  - Assembly-CSharp
  namespace: TaleOfTiles.Journey
  syntax:
    content: public JourneyMapBlock.JourneyMapBlockConfig[] blocks
    return:
      type: TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig[]
    content.vb: Public blocks As JourneyMapBlock.JourneyMapBlockConfig()
- uid: TaleOfTiles.Journey.JourneyMapConfig.#ctor(System.String,System.String,TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig[])
  commentId: M:TaleOfTiles.Journey.JourneyMapConfig.#ctor(System.String,System.String,TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig[])
  id: '#ctor(System.String,System.String,TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig[])'
  parent: TaleOfTiles.Journey.JourneyMapConfig
  langs:
  - csharp
  - vb
  name: JourneyMapConfig(string, string, JourneyMapBlockConfig[])
  nameWithType: JourneyMapConfig.JourneyMapConfig(string, string, JourneyMapBlock.JourneyMapBlockConfig[])
  fullName: TaleOfTiles.Journey.JourneyMapConfig.JourneyMapConfig(string, string, TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig[])
  type: Constructor
  source:
    remote:
      path: Assets/Scripts/LevelGenerator/JourneyMap.cs
      branch: dev
      repo: https://github.com/ElementalMagic/Match-3-Mobile-Game.git
    id: .ctor
    path: ../Assets/Scripts/LevelGenerator/JourneyMap.cs
    startLine: 75
  assemblies:
  - Assembly-CSharp
  namespace: TaleOfTiles.Journey
  syntax:
    content: public JourneyMapConfig(string config_id, string map_id, JourneyMapBlock.JourneyMapBlockConfig[] blocks)
    parameters:
    - id: config_id
      type: System.String
    - id: map_id
      type: System.String
    - id: blocks
      type: TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig[]
    content.vb: Public Sub New(config_id As String, map_id As String, blocks As JourneyMapBlock.JourneyMapBlockConfig())
  overload: TaleOfTiles.Journey.JourneyMapConfig.#ctor*
  nameWithType.vb: JourneyMapConfig.New(String, String, JourneyMapBlock.JourneyMapBlockConfig())
  fullName.vb: TaleOfTiles.Journey.JourneyMapConfig.New(String, String, TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig())
  name.vb: New(String, String, JourneyMapBlockConfig())
references:
- uid: TaleOfTiles.Journey
  commentId: N:TaleOfTiles.Journey
  href: TaleOfTiles.html
  name: TaleOfTiles.Journey
  nameWithType: TaleOfTiles.Journey
  fullName: TaleOfTiles.Journey
  spec.csharp:
  - uid: TaleOfTiles
    name: TaleOfTiles
    href: TaleOfTiles.html
  - name: .
  - uid: TaleOfTiles.Journey
    name: Journey
    href: TaleOfTiles.Journey.html
  spec.vb:
  - uid: TaleOfTiles
    name: TaleOfTiles
    href: TaleOfTiles.html
  - name: .
  - uid: TaleOfTiles.Journey
    name: Journey
    href: TaleOfTiles.Journey.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig[]
  isExternal: true
  href: TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig.html
  name: JourneyMapBlockConfig[]
  nameWithType: JourneyMapBlock.JourneyMapBlockConfig[]
  fullName: TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig[]
  nameWithType.vb: JourneyMapBlock.JourneyMapBlockConfig()
  fullName.vb: TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig()
  name.vb: JourneyMapBlockConfig()
  spec.csharp:
  - uid: TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig
    name: JourneyMapBlockConfig
    href: TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig.html
  - name: '['
  - name: ']'
  spec.vb:
  - uid: TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig
    name: JourneyMapBlockConfig
    href: TaleOfTiles.Journey.JourneyMapBlock.JourneyMapBlockConfig.html
  - name: (
  - name: )
- uid: TaleOfTiles.Journey.JourneyMapConfig.#ctor*
  commentId: Overload:TaleOfTiles.Journey.JourneyMapConfig.#ctor
  href: TaleOfTiles.Journey.JourneyMapConfig.html#TaleOfTiles_Journey_JourneyMapConfig__ctor_System_String_System_String_TaleOfTiles_Journey_JourneyMapBlock_JourneyMapBlockConfig___
  name: JourneyMapConfig
  nameWithType: JourneyMapConfig.JourneyMapConfig
  fullName: TaleOfTiles.Journey.JourneyMapConfig.JourneyMapConfig
  nameWithType.vb: JourneyMapConfig.New
  fullName.vb: TaleOfTiles.Journey.JourneyMapConfig.New
  name.vb: New
